# Generated by Django 5.2.6 on 2025-11-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLente',
            fields=[
                ('id_configuracion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('curva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duracion_meses', models.SmallIntegerField()),
                ('material', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'configuracion_lente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('medida', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado_producto', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
