# Generated by Django 5.2.6 on 2025-11-04 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='fecha_hora')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGOUT_ERROR', 'Error al cerrar sesión'), ('FAILED_LOGIN', 'Intento fallido de inicio de sesión'), ('TOKEN_INVALIDATION', 'Invalidación de token'), ('REGISTER', 'Registro de usuario'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Reseteo de contraseña'), ('PROFILE_UPDATE', 'Actualización de perfil'), ('DELETE_ACCOUNT', 'Eliminación de cuenta'), ('PERMISSION_CHANGE', 'Cambio de permisos'), ('VIEW_ACCESS', 'Acceso a vista'), ('PAGE_VIEW', 'Vista de página'), ('PRODUCT_VIEW', 'Vista de producto'), ('ANONYMOUS_VIEW', 'Vista de usuario anónimo'), ('ANONYMOUS_PRODUCT_VIEW', 'Vista de producto por usuario anónimo'), ('ANONYMOUS_SEARCH', 'Búsqueda por usuario anónimo'), ('CATEGORY_CREATE', 'Creación de categoría'), ('CATEGORY_UPDATE', 'Actualización de categoría'), ('CATEGORY_MOVE', 'Movimiento de categoría'), ('CATEGORY_DELETE', 'Eliminación lógica de categoría'), ('CATEGORY_RESTORE', 'Restauración de categoría'), ('PRODUCT_CREATE', 'Creación de producto'), ('PRODUCT_UPDATE', 'Actualización de producto'), ('PRODUCT_DELETE', 'Eliminación de producto'), ('PRODUCT_STATE_CHANGE', 'Cambio de estado de producto'), ('PRODUCT_STOCK_ADJUST', 'Ajuste de stock de producto'), ('IMAGE_UPLOAD', 'Subida de imagen de producto'), ('IMAGE_DELETE', 'Eliminación de imagen de producto'), ('IMAGE_SET_MAIN', 'Cambio de imagen principal'), ('IMAGE_REORDER', 'Reordenamiento de imágenes'), ('IMAGE_RESTORE', 'Restauración de imagen de producto'), ('IMAGE_UPDATE', 'Actualización de metadatos de imagen'), ('ADDRESS_CREATE', 'Creación de dirección de cliente'), ('ADDRESS_UPDATE', 'Actualización de dirección de cliente'), ('ADDRESS_DELETE', 'Eliminación de dirección de cliente'), ('ADDRESS_SET_PRINCIPAL', 'Cambio de dirección principal'), ('ROLE_CREATED', 'Creación de rol'), ('ROLE_UPDATED', 'Actualización de rol'), ('ROLE_DELETED', 'Eliminación de rol'), ('PERMISSION_CREATED', 'Creación de permiso'), ('PERMISSION_UPDATED', 'Actualización de permiso'), ('PERMISSION_DELETED', 'Eliminación de permiso'), ('PERMISSION_ASSIGNED_TO_ROLE', 'Asignación de permiso a rol'), ('PERMISSION_REMOVED_FROM_ROLE', 'Remoción de permiso de rol'), ('PERMISSION_GRANTED_TO_USER', 'Concesión de permiso individual a usuario'), ('PERMISSION_REVOKED_FROM_USER', 'Revocación de permiso individual de usuario'), ('ERROR_404', 'Página no encontrada'), ('ERROR_500', 'Error interno del servidor'), ('SUSPICIOUS_ACTIVITY', 'Actividad sospechosa')], max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
