# Generated by Django 5.2.6 on 2025-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('cod_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_envio', models.CharField(choices=[('EN_PREPARACION', 'En preparación'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=15)),
            ],
            options={
                'db_table': 'envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('cod_tipo_envio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_envio',
                'managed': False,
            },
        ),
    ]
