# Generated by Django 5.2.6 on 2025-10-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=90)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(db_column='contraseña', max_length=255, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField()),
                ('estado_usuario', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='clientes.usuarios')),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
