# Generated by Django 5.2.6 on 2025-11-02 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(help_text='Asunto o título del ticket', max_length=200)),
                ('tipo_consulta', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('DUDA', 'Duda sobre producto'), ('PEDIDO', 'Problema con pedido'), ('SUGERENCIA', 'Sugerencia'), ('OTRO', 'Otro')], help_text='Tipo de consulta (reclamo, duda, sugerencia, etc.)', max_length=20)),
                ('mensaje', models.TextField(help_text='Mensaje inicial del ticket')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], default='PENDIENTE', help_text='Estado actual del ticket', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_agente_asignado', models.ForeignKey(blank=True, db_column='id_agente_asignado', help_text='Agente de soporte asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', help_text='Cliente que creó el ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'ticket',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeTicket',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('es_respuesta_agente', models.BooleanField(default=False, help_text='True si el mensaje fue enviado por un agente de soporte')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Usuario que envió el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket al que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='soporte.ticket')),
            ],
            options={
                'verbose_name': 'Mensaje de Ticket',
                'verbose_name_plural': 'Mensajes de Tickets',
                'db_table': 'mensaje_ticket',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='ticket_estado_3dd1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['id_cliente', '-fecha_creacion'], name='ticket_id_clie_1081c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeticket',
            index=models.Index(fields=['ticket', 'fecha_envio'], name='mensaje_tic_ticket__1db447_idx'),
        ),
    ]
