# Generated by Django 5.2.6 on 2025-10-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Dirección IP')),
                ('razon', models.TextField(verbose_name='Razón del bloqueo')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de bloqueo')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('bloqueada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_bloqueadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'db_table': 'ip_blacklist',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('exitoso', models.BooleanField(default=False, verbose_name='¿Exitoso?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'login_attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip', 'timestamp'], name='login_attem_ip_5f6e76_idx'), models.Index(fields=['usuario', 'timestamp'], name='login_attem_usuario_8f50c4_idx')],
            },
        ),
    ]
