# Generated by Django 5.2.6 on 2025-11-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='productos.producto')),
            ],
            options={
                'db_table': 'lote',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
