# Generated by Django 5.2.6 on 2025-11-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'managed': False, 'ordering': ['fecha_vencimiento']},
        ),
    ]
