# Generated by Django 5.2.6 on 2025-10-10 05:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=90)),
                ('nombre_usuario', models.CharField(max_length=35, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_usuario', models.CharField(default='ACTIVO', max_length=10)),
                ('rol', models.CharField(max_length=20)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.OneToOneField(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_contrato', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.OneToOneField(db_column='id_vendedor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_contrato', models.DateField(default=django.utils.timezone.now)),
                ('tipo_vendedor', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
    ]
