# Generated by Django 5.2.6 on 2025-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('guardada', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'direccion_cliente',
                'ordering': ['-es_principal', '-fecha_creacion'],
                'managed': False,
            },
        ),
    ]
