# Generated by Django 5.2.6 on 2025-11-02 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('public_id', models.CharField(max_length=150, unique=True)),
                ('formato', models.CharField(max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado_imagen', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
                ('subido_por', models.ForeignKey(db_column='subido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imagen_producto',
                'ordering': ['orden', 'id_imagen'],
                'indexes': [models.Index(fields=['id_producto', 'es_principal'], name='imagen_prod_id_prod_d54dfd_idx'), models.Index(fields=['public_id'], name='imagen_prod_public__e7c2a8_idx')],
                'unique_together': {('id_producto', 'orden')},
            },
        ),
    ]
