# Generated by Django 5.2.6 on 2025-11-01 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre único del permiso (ej: productos.crear)', max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código interno del permiso (ej: PRODUCT_CREATE)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del permiso y su alcance', null=True)),
                ('modulo', models.CharField(help_text='Módulo al que pertenece (ej: productos, usuarios, ventas)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, el permiso no se puede asignar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre único del rol (ej: ADMINISTRADOR)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol y sus responsabilidades', null=True)),
                ('es_sistema', models.BooleanField(default=False, help_text='Roles del sistema no se pueden eliminar')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se puede asignar a usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'rol_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id_usuario_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('concedido', models.BooleanField(default=True, help_text='True: Conceder permiso adicional | False: Revocar permiso del rol')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha opcional de expiración del permiso', null=True)),
                ('motivo', models.TextField(blank=True, help_text='Razón por la cual se asignó/revocó el permiso', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Permite desactivar temporalmente sin eliminar')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_asignados_a_otros', to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_usuarios', to='seguridad.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Permiso Individual',
                'verbose_name_plural': 'Usuarios-Permisos Individuales',
                'db_table': 'usuario_permiso',
                'managed': True,
                'indexes': [models.Index(fields=['usuario', 'permiso'], name='usuario_per_usuario_401e0d_idx'), models.Index(fields=['usuario', 'activo'], name='usuario_per_usuario_5e2448_idx'), models.Index(fields=['fecha_expiracion'], name='usuario_per_fecha_e_79d85e_idx')],
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
