# Generated by Django 5.2.6 on 2025-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado_categoria', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
